# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "ksucs-hugo-theme"
license = "MIT"
licenselink = "https://github.com/russfeld/ksucs-hugo-theme/blob/master/LICENSE.md"
description = "Documentation theme for Hugo, based on Grav Learn theme"
homepage = "https://github.com/russfeld/ksucs-hugo-theme/"
repo = "https://github.com/russfeld/ksucs-hugo-theme"
tags = ["documentation", "grav", "learn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Russell Feldhausen"
  homepage = "https://russfeld.me/"

[original]
  name = "Hugo Theme Learn"
  homepage = "https://github.com/matcornic/hugo-theme-learn/"
  repo = "https://github.com/matcornic/hugo-theme-learn/"
